default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: root
  password: <%= ENV['MEGAMAP_DATABASE_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: megamap_development

test:
  <<: *default
  database: megamap_test

production:
  url: <%= ENV['MEGAMAP_DATABASE_URL'] %>
